[package]
name = "hex_snake"
version = "0.1.0"
authors = ["gorilskij <43991400@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"
mint = "0.5.4"
rand = "0.7.2"
tuple = "0.4.2"
derive_more = "0.99.2"
num = "0.2.1"