[package]
name = "hex_snake"
version = "0.1.0"
authors = ["gorilskij <43991400@users.noreply.github.com>"]
edition = "2018"

[dependencies]
ggez = { git = "https://github.com/ggez/ggez", rev = "63e246d" }
#ggez = { git = "https://github.com/ggez/ggez" }
#ggez = { git = "https://github.com/ggez/ggez", branch = "devel" }
rand = "~0.7"
itertools = "0.10"
derive_more = "~0.99"
num-integer = "~0.1"
hsl = "0.1.1"
lazy_static = "1.4.0"
itertools-num = "0.1.3"
num-traits = "0.2"
#smallvec = "1.6.1"

[profile.release]
debug = true

[features]
default = ["show_search_path"]
show_search_path = []