[package]
name = "hex_snake"
version = "0.1.0"
authors = ["gorilskij <43991400@users.noreply.github.com>"]
edition = "2018"

[dependencies]
ggez = "0.5.1"
mint = "~0.5"
rand = "~0.7"
tuple = "~0.4"
derive_more = "~0.99"
num-integer = "~0.1"
itertools = "0.9.0"